### ISSUE TITLE
decode_reader doesn't work with socket

### ISSUE THREAD

**Issue by davidmatson** [mohanson/leb128#7]
The use of typing.BinaryIO doesn't work with a connected (client) socket:
```
leb128.u.decode_reader(cs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python310\lib\site-packages\leb128\__init__.py", line 43, in decode_reader
    b = ord(r.read(1))
AttributeError: 'socket' object has no attribute 'read'
```

Would a [Protocol](https://docs.python.org/3/library/typing.html#typing.Protocol) work more elegantly for that case?

**Comment by mohanson** [comment]
`socket` is a Low-level networking interface and it is not a valid IO object.

You need to call the `makefile` on it:

```python
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    f = s.makefile()              # <-------------------- Here!
    leb128.u.decode_reader(f)
```

**Comment by davidmatson** [comment]
Thanks, @mohanson.

Would switching to a lighter-weight Protocol, rather than a full typing.BinaryIO object, still make sense? (Might that avoid the need to create a file object out of a socket?)

**Comment by mohanson** [comment]
No, the most classic use of leb128 is to read wasm files and dwarf files, so IO is the most suitable typing hints
