### ISSUE TITLE
Feature request: publish a wheel

### ISSUE THREAD

**Issue by agriyakhetarpal** [mohanson/leb128#8]
It looks like this package is being used as a dependency for `pyodide-build`, and the package provides a source distribution (`.tar.gz`).

It would be great to receive wheels when downloading from PyPI rather than `sdist`s. Since the package is pure Python, building a wheel here should be trivial.

**Comment by mohanson** [comment]
Thank you for your request.

I've replaced `setup.py` with `pyproject.toml` for project builds, and now it automatically publishes wheel on Pypi.

See: https://pypi.org/project/leb128/#files

**Comment by agriyakhetarpal** [comment]
Also, it doesn't take long for `pip` to build a wheel for `leb128`, really. My recommendation comes from https://pythonwheels.com/, which on 07/03/2024 mentions that 359/360 top Python packages have wheels.

**Comment by bollwyvl** [comment]
Corollary: the last few releases don't have git [tags](https://github.com/mohanson/leb128/tags) which would be lovely for downstreams (e.g. https://github.com/conda-forge/leb128-feedstock/pull/2) to assess what might have changed at a packaging level (build systems, etc.)

**Comment by mohanson** [comment]
> Corollary: the last few releases don't have git [tags](https://github.com/mohanson/leb128/tags) which would be lovely for downstreams (e.g. [conda-forge/leb128-feedstock#2](https://github.com/conda-forge/leb128-feedstock/pull/2)) to assess what might have changed at a packaging level (build systems, etc.)

I have posted tags.

**Comment by agriyakhetarpal** [comment]
Thanks @bollwyvl and @mohanson for the discussion and for publishing wheels. I suppose this issue can now be closed.
